// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function localized(value, language = "en") {
  if (typeof value === "string") return value;
  if (value && typeof value === "object") {
    const map = value;
    const picked = map[language] ?? map.en ?? map.da ?? Object.values(map)[0];
    if (typeof picked === "string") return picked;
  }
  return "";
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-projects.ts
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List the signed-in user's PRISM projects with their status, DNA code and whether a morphological assessment exists.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter, e.g. 'active'."),
    language: z.string().optional().describe("Language for names/descriptions: 'en' or 'da'. Defaults to 'en'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, language }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("projects").select("id, name, description, status, dna_code, team_size, timeline_start, timeline_end, morphology, is_demo, updated_at").order("updated_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const projects = (data ?? []).map((p) => ({
      id: p.id,
      name: localized(p.name, language),
      description: localized(p.description, language),
      status: p.status,
      dna_code: p.dna_code,
      team_size: p.team_size,
      timeline_start: p.timeline_start,
      timeline_end: p.timeline_end,
      assessed: !!p.morphology && Object.keys(p.morphology).length > 0,
      is_demo: p.is_demo,
      updated_at: p.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
      structuredContent: { projects, count: projects.length }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Get one PRISM project in full: morphological assessment (12 dimensions), DNA code, detected patterns and Theory-U analysis.",
  inputSchema: {
    project_id: z2.string().uuid().describe("The project id."),
    language: z2.string().optional().describe("Language for names/descriptions: 'en' or 'da'. Defaults to 'en'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, language }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("projects").select("*").eq("id", project_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Project not found." }], isError: true };
    }
    const project = {
      id: data.id,
      name: localized(data.name, language),
      description: localized(data.description, language),
      status: data.status,
      dna_code: data.dna_code,
      team_size: data.team_size,
      timeline_start: data.timeline_start,
      timeline_end: data.timeline_end,
      morphology: data.morphology,
      patterns: data.patterns,
      theory_u_analysis: data.theory_u_analysis,
      is_demo: data.is_demo,
      created_at: data.created_at,
      updated_at: data.updated_at
    };
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/list-blind-spots.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_blind_spots_default = defineTool3({
  name: "list_blind_spots",
  title: "List blind spots",
  description: "List AI-detected blind spots for one project, with priority, confidence, consequences and recommended actions.",
  inputSchema: {
    project_id: z3.string().uuid().describe("The project id."),
    status: z3.string().optional().describe("Optional status filter: 'unaddressed', 'acknowledged' or 'addressed'."),
    priority: z3.string().optional().describe("Optional priority filter: 'high', 'medium' or 'low'."),
    language: z3.string().optional().describe("Language for text fields: 'en' or 'da'. Defaults to 'en'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, status, priority, language }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("blind_spots").select("id, project_id, title, description, priority, confidence, consequences, recommendations, status, detected_at").eq("project_id", project_id).order("detected_at", { ascending: false });
    if (status) query = query.eq("status", status);
    if (priority) query = query.eq("priority", priority);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const blindSpots = (data ?? []).map((b) => ({
      id: b.id,
      project_id: b.project_id,
      title: localized(b.title, language),
      description: localized(b.description, language),
      priority: b.priority,
      confidence: b.confidence,
      consequences: b.consequences,
      recommendations: b.recommendations,
      status: b.status,
      detected_at: b.detected_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(blindSpots, null, 2) }],
      structuredContent: { blind_spots: blindSpots, count: blindSpots.length }
    };
  }
});

// src/lib/mcp/tools/update-blind-spot-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var update_blind_spot_status_default = defineTool4({
  name: "update_blind_spot_status",
  title: "Update blind spot status",
  description: "Set a blind spot's status to unaddressed, acknowledged or addressed for the signed-in user's project.",
  inputSchema: {
    blind_spot_id: z4.string().uuid().describe("The blind spot id."),
    status: z4.enum(["unaddressed", "acknowledged", "addressed"]).describe("The new status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ blind_spot_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("blind_spots").update({
      status,
      addressed_at: status === "addressed" ? (/* @__PURE__ */ new Date()).toISOString() : null
    }).eq("id", blind_spot_id).select("id, status, addressed_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Blind spot not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Blind spot ${data.id} is now ${data.status}.` }],
      structuredContent: { blind_spot: data }
    };
  }
});

// src/lib/mcp/tools/list-project-documents.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var MAX_CONTENT_CHARS = 8e3;
var list_project_documents_default = defineTool5({
  name: "list_project_documents",
  title: "List project documents",
  description: "List the documents uploaded to a project. Optionally include the extracted text content (truncated per document).",
  inputSchema: {
    project_id: z5.string().uuid().describe("The project id."),
    include_content: z5.boolean().optional().describe("Include extracted text content for each processed document. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ project_id, include_content }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("documents").select("id, filename, file_type, file_size, processed, language, metadata, uploaded_at, content").eq("project_id", project_id).order("uploaded_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const documents = (data ?? []).map((d) => {
      const base = {
        id: d.id,
        filename: d.filename,
        file_type: d.file_type,
        file_size: d.file_size,
        processed: d.processed,
        language: d.language,
        metadata: d.metadata,
        uploaded_at: d.uploaded_at
      };
      if (!include_content) return base;
      const content = d.content ?? "";
      return {
        ...base,
        content: content.length > MAX_CONTENT_CHARS ? `${content.slice(0, MAX_CONTENT_CHARS)}... [truncated]` : content
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(documents, null, 2) }],
      structuredContent: { documents, count: documents.length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ztyogejxlprnqxgoekml";
var mcp_default = defineMcp({
  name: "project-insights",
  title: "Project Insights",
  version: "0.1.0",
  instructions: "Tools for PRISM (Project Insights), a project intelligence platform. Use `list_projects` to find the signed-in user's projects, `get_project` for the 12-dimension morphological assessment, DNA code, patterns and Theory-U analysis, `list_blind_spots` for AI-detected blind spots with recommendations, `update_blind_spot_status` to mark one acknowledged or addressed, and `list_project_documents` to inspect uploaded source documents.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, get_project_default, list_blind_spots_default, update_blind_spot_status_default, list_project_documents_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
